// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: proto/schedule.proto

package schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{0}
}

type Faculty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Faculty) Reset() {
	*x = Faculty{}
	mi := &file_proto_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Faculty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faculty) ProtoMessage() {}

func (x *Faculty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faculty.ProtoReflect.Descriptor instead.
func (*Faculty) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *Faculty) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Faculty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FacultyId     int32                  `protobuf:"varint,3,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	EduFormId     int32                  `protobuf:"varint,4,opt,name=edu_form_id,json=eduFormId,proto3" json:"edu_form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetFacultyId() int32 {
	if x != nil {
		return x.FacultyId
	}
	return 0
}

func (x *Group) GetEduFormId() int32 {
	if x != nil {
		return x.EduFormId
	}
	return 0
}

type ScheduleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	LessonNum     int32                  `protobuf:"varint,4,opt,name=lesson_num,json=lessonNum,proto3" json:"lesson_num,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Teacher       string                 `protobuf:"bytes,6,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Room          string                 `protobuf:"bytes,7,opt,name=room,proto3" json:"room,omitempty"`
	StartTime     string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Mode          string                 `protobuf:"bytes,10,opt,name=mode,proto3" json:"mode,omitempty"`
	Subgroup      int32                  `protobuf:"varint,11,opt,name=subgroup,proto3" json:"subgroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleItem) Reset() {
	*x = ScheduleItem{}
	mi := &file_proto_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleItem) ProtoMessage() {}

func (x *ScheduleItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleItem.ProtoReflect.Descriptor instead.
func (*ScheduleItem) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScheduleItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ScheduleItem) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ScheduleItem) GetLessonNum() int32 {
	if x != nil {
		return x.LessonNum
	}
	return 0
}

func (x *ScheduleItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ScheduleItem) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *ScheduleItem) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ScheduleItem) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleItem) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleItem) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ScheduleItem) GetSubgroup() int32 {
	if x != nil {
		return x.Subgroup
	}
	return 0
}

type FacultiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculties     []*Faculty             `protobuf:"bytes,1,rep,name=faculties,proto3" json:"faculties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacultiesResponse) Reset() {
	*x = FacultiesResponse{}
	mi := &file_proto_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacultiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacultiesResponse) ProtoMessage() {}

func (x *FacultiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacultiesResponse.ProtoReflect.Descriptor instead.
func (*FacultiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *FacultiesResponse) GetFaculties() []*Faculty {
	if x != nil {
		return x.Faculties
	}
	return nil
}

type GroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacultyId     int32                  `protobuf:"varint,1,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	EduFormId     int32                  `protobuf:"varint,2,opt,name=edu_form_id,json=eduFormId,proto3" json:"edu_form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsRequest) Reset() {
	*x = GroupsRequest{}
	mi := &file_proto_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsRequest) ProtoMessage() {}

func (x *GroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsRequest.ProtoReflect.Descriptor instead.
func (*GroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *GroupsRequest) GetFacultyId() int32 {
	if x != nil {
		return x.FacultyId
	}
	return 0
}

func (x *GroupsRequest) GetEduFormId() int32 {
	if x != nil {
		return x.EduFormId
	}
	return 0
}

type GroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsResponse) Reset() {
	*x = GroupsResponse{}
	mi := &file_proto_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsResponse) ProtoMessage() {}

func (x *GroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsResponse.ProtoReflect.Descriptor instead.
func (*GroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *GroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_proto_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      []*ScheduleItem        `protobuf:"bytes,1,rep,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_proto_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleResponse) GetSchedule() []*ScheduleItem {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type LastUpdatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       map[string]string      `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastUpdatedResponse) Reset() {
	*x = LastUpdatedResponse{}
	mi := &file_proto_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastUpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastUpdatedResponse) ProtoMessage() {}

func (x *LastUpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastUpdatedResponse.ProtoReflect.Descriptor instead.
func (*LastUpdatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *LastUpdatedResponse) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type SGUPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculty       string                 `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Form          string                 `protobuf:"bytes,2,opt,name=form,proto3" json:"form,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGUPathRequest) Reset() {
	*x = SGUPathRequest{}
	mi := &file_proto_schedule_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGUPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGUPathRequest) ProtoMessage() {}

func (x *SGUPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGUPathRequest.ProtoReflect.Descriptor instead.
func (*SGUPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{10}
}

func (x *SGUPathRequest) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *SGUPathRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *SGUPathRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_proto_schedule_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{11}
}

func (x *ScrapeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ScrapeStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Running        bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	LastTrigger    string                 `protobuf:"bytes,2,opt,name=last_trigger,json=lastTrigger,proto3" json:"last_trigger,omitempty"`
	LastStartedAt  string                 `protobuf:"bytes,3,opt,name=last_started_at,json=lastStartedAt,proto3" json:"last_started_at,omitempty"`
	LastFinishedAt string                 `protobuf:"bytes,4,opt,name=last_finished_at,json=lastFinishedAt,proto3" json:"last_finished_at,omitempty"`
	LastDurationMs int64                  `protobuf:"varint,5,opt,name=last_duration_ms,json=lastDurationMs,proto3" json:"last_duration_ms,omitempty"`
	LastError      string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScrapeStatusResponse) Reset() {
	*x = ScrapeStatusResponse{}
	mi := &file_proto_schedule_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeStatusResponse) ProtoMessage() {}

func (x *ScrapeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeStatusResponse.ProtoReflect.Descriptor instead.
func (*ScrapeStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{12}
}

func (x *ScrapeStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ScrapeStatusResponse) GetLastTrigger() string {
	if x != nil {
		return x.LastTrigger
	}
	return ""
}

func (x *ScrapeStatusResponse) GetLastStartedAt() string {
	if x != nil {
		return x.LastStartedAt
	}
	return ""
}

func (x *ScrapeStatusResponse) GetLastFinishedAt() string {
	if x != nil {
		return x.LastFinishedAt
	}
	return ""
}

func (x *ScrapeStatusResponse) GetLastDurationMs() int64 {
	if x != nil {
		return x.LastDurationMs
	}
	return 0
}

func (x *ScrapeStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_proto_schedule_proto protoreflect.FileDescriptor

const file_proto_schedule_proto_rawDesc = "" +
	"\n" +
	"\x14proto/schedule.proto\x12\bschedule\"\a\n" +
	"\x05Empty\"-\n" +
	"\aFaculty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"j\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x03 \x01(\x05R\tfacultyId\x12\x1e\n" +
	"\vedu_form_id\x18\x04 \x01(\x05R\teduFormId\"\xaa\x02\n" +
	"\fScheduleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"lesson_num\x18\x04 \x01(\x05R\tlessonNum\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\ateacher\x18\x06 \x01(\tR\ateacher\x12\x12\n" +
	"\x04room\x18\a \x01(\tR\x04room\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x12\n" +
	"\x04mode\x18\n" +
	" \x01(\tR\x04mode\x12\x1a\n" +
	"\bsubgroup\x18\v \x01(\x05R\bsubgroup\"D\n" +
	"\x11FacultiesResponse\x12/\n" +
	"\tfaculties\x18\x01 \x03(\v2\x11.schedule.FacultyR\tfaculties\"N\n" +
	"\rGroupsRequest\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x01 \x01(\x05R\tfacultyId\x12\x1e\n" +
	"\vedu_form_id\x18\x02 \x01(\x05R\teduFormId\"9\n" +
	"\x0eGroupsResponse\x12'\n" +
	"\x06groups\x18\x01 \x03(\v2\x0f.schedule.GroupR\x06groups\",\n" +
	"\x0fScheduleRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"F\n" +
	"\x10ScheduleResponse\x122\n" +
	"\bschedule\x18\x01 \x03(\v2\x16.schedule.ScheduleItemR\bschedule\"\x97\x01\n" +
	"\x13LastUpdatedResponse\x12D\n" +
	"\aupdates\x18\x01 \x03(\v2*.schedule.LastUpdatedResponse.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x0eSGUPathRequest\x12\x18\n" +
	"\afaculty\x18\x01 \x01(\tR\afaculty\x12\x12\n" +
	"\x04form\x18\x02 \x01(\tR\x04form\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"*\n" +
	"\x0eScrapeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xee\x01\n" +
	"\x14ScrapeStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12!\n" +
	"\flast_trigger\x18\x02 \x01(\tR\vlastTrigger\x12&\n" +
	"\x0flast_started_at\x18\x03 \x01(\tR\rlastStartedAt\x12(\n" +
	"\x10last_finished_at\x18\x04 \x01(\tR\x0elastFinishedAt\x12(\n" +
	"\x10last_duration_ms\x18\x05 \x01(\x03R\x0elastDurationMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError2\xde\x03\n" +
	"\x0fScheduleService\x12<\n" +
	"\fGetFaculties\x12\x0f.schedule.Empty\x1a\x1b.schedule.FacultiesResponse\x12>\n" +
	"\tGetGroups\x12\x17.schedule.GroupsRequest\x1a\x18.schedule.GroupsResponse\x12D\n" +
	"\vGetSchedule\x12\x19.schedule.ScheduleRequest\x1a\x1a.schedule.ScheduleResponse\x12@\n" +
	"\x0eGetLastUpdated\x12\x0f.schedule.Empty\x1a\x1d.schedule.LastUpdatedResponse\x12I\n" +
	"\x11GetScheduleByPath\x12\x18.schedule.SGUPathRequest\x1a\x1a.schedule.ScheduleResponse\x126\n" +
	"\tRunScrape\x12\x0f.schedule.Empty\x1a\x18.schedule.ScrapeResponse\x12B\n" +
	"\x0fGetScrapeStatus\x12\x0f.schedule.Empty\x1a\x1e.schedule.ScrapeStatusResponseB\x12Z\x10./proto;scheduleb\x06proto3"

var (
	file_proto_schedule_proto_rawDescOnce sync.Once
	file_proto_schedule_proto_rawDescData []byte
)

func file_proto_schedule_proto_rawDescGZIP() []byte {
	file_proto_schedule_proto_rawDescOnce.Do(func() {
		file_proto_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schedule_proto_rawDesc), len(file_proto_schedule_proto_rawDesc)))
	})
	return file_proto_schedule_proto_rawDescData
}

var file_proto_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_schedule_proto_goTypes = []any{
	(*Empty)(nil),                // 0: schedule.Empty
	(*Faculty)(nil),              // 1: schedule.Faculty
	(*Group)(nil),                // 2: schedule.Group
	(*ScheduleItem)(nil),         // 3: schedule.ScheduleItem
	(*FacultiesResponse)(nil),    // 4: schedule.FacultiesResponse
	(*GroupsRequest)(nil),        // 5: schedule.GroupsRequest
	(*GroupsResponse)(nil),       // 6: schedule.GroupsResponse
	(*ScheduleRequest)(nil),      // 7: schedule.ScheduleRequest
	(*ScheduleResponse)(nil),     // 8: schedule.ScheduleResponse
	(*LastUpdatedResponse)(nil),  // 9: schedule.LastUpdatedResponse
	(*SGUPathRequest)(nil),       // 10: schedule.SGUPathRequest
	(*ScrapeResponse)(nil),       // 11: schedule.ScrapeResponse
	(*ScrapeStatusResponse)(nil), // 12: schedule.ScrapeStatusResponse
	nil,                          // 13: schedule.LastUpdatedResponse.UpdatesEntry
}
var file_proto_schedule_proto_depIdxs = []int32{
	1,  // 0: schedule.FacultiesResponse.faculties:type_name -> schedule.Faculty
	2,  // 1: schedule.GroupsResponse.groups:type_name -> schedule.Group
	3,  // 2: schedule.ScheduleResponse.schedule:type_name -> schedule.ScheduleItem
	13, // 3: schedule.LastUpdatedResponse.updates:type_name -> schedule.LastUpdatedResponse.UpdatesEntry
	0,  // 4: schedule.ScheduleService.GetFaculties:input_type -> schedule.Empty
	5,  // 5: schedule.ScheduleService.GetGroups:input_type -> schedule.GroupsRequest
	7,  // 6: schedule.ScheduleService.GetSchedule:input_type -> schedule.ScheduleRequest
	0,  // 7: schedule.ScheduleService.GetLastUpdated:input_type -> schedule.Empty
	10, // 8: schedule.ScheduleService.GetScheduleByPath:input_type -> schedule.SGUPathRequest
	0,  // 9: schedule.ScheduleService.RunScrape:input_type -> schedule.Empty
	0,  // 10: schedule.ScheduleService.GetScrapeStatus:input_type -> schedule.Empty
	4,  // 11: schedule.ScheduleService.GetFaculties:output_type -> schedule.FacultiesResponse
	6,  // 12: schedule.ScheduleService.GetGroups:output_type -> schedule.GroupsResponse
	8,  // 13: schedule.ScheduleService.GetSchedule:output_type -> schedule.ScheduleResponse
	9,  // 14: schedule.ScheduleService.GetLastUpdated:output_type -> schedule.LastUpdatedResponse
	8,  // 15: schedule.ScheduleService.GetScheduleByPath:output_type -> schedule.ScheduleResponse
	11, // 16: schedule.ScheduleService.RunScrape:output_type -> schedule.ScrapeResponse
	12, // 17: schedule.ScheduleService.GetScrapeStatus:output_type -> schedule.ScrapeStatusResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_schedule_proto_init() }
func file_proto_schedule_proto_init() {
	if File_proto_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schedule_proto_rawDesc), len(file_proto_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_schedule_proto_goTypes,
		DependencyIndexes: file_proto_schedule_proto_depIdxs,
		MessageInfos:      file_proto_schedule_proto_msgTypes,
	}.Build()
	File_proto_schedule_proto = out.File
	file_proto_schedule_proto_goTypes = nil
	file_proto_schedule_proto_depIdxs = nil
}
