// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: proto/schedule.proto

package schedule

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduleService_GetFaculties_FullMethodName      = "/schedule.ScheduleService/GetFaculties"
	ScheduleService_GetGroups_FullMethodName         = "/schedule.ScheduleService/GetGroups"
	ScheduleService_GetSchedule_FullMethodName       = "/schedule.ScheduleService/GetSchedule"
	ScheduleService_GetLastUpdated_FullMethodName    = "/schedule.ScheduleService/GetLastUpdated"
	ScheduleService_GetScheduleByPath_FullMethodName = "/schedule.ScheduleService/GetScheduleByPath"
	ScheduleService_RunScrape_FullMethodName         = "/schedule.ScheduleService/RunScrape"
	ScheduleService_GetScrapeStatus_FullMethodName   = "/schedule.ScheduleService/GetScrapeStatus"
)

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleServiceClient interface {
	GetFaculties(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FacultiesResponse, error)
	GetGroups(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*GroupsResponse, error)
	GetSchedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	GetLastUpdated(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LastUpdatedResponse, error)
	GetScheduleByPath(ctx context.Context, in *SGUPathRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	RunScrape(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScrapeResponse, error)
	GetScrapeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScrapeStatusResponse, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) GetFaculties(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FacultiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FacultiesResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetFaculties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetGroups(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*GroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupsResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetSchedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetLastUpdated(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LastUpdatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastUpdatedResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetLastUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetScheduleByPath(ctx context.Context, in *SGUPathRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetScheduleByPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) RunScrape(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeResponse)
	err := c.cc.Invoke(ctx, ScheduleService_RunScrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetScrapeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScrapeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeStatusResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetScrapeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations must embed UnimplementedScheduleServiceServer
// for forward compatibility.
type ScheduleServiceServer interface {
	GetFaculties(context.Context, *Empty) (*FacultiesResponse, error)
	GetGroups(context.Context, *GroupsRequest) (*GroupsResponse, error)
	GetSchedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	GetLastUpdated(context.Context, *Empty) (*LastUpdatedResponse, error)
	GetScheduleByPath(context.Context, *SGUPathRequest) (*ScheduleResponse, error)
	RunScrape(context.Context, *Empty) (*ScrapeResponse, error)
	GetScrapeStatus(context.Context, *Empty) (*ScrapeStatusResponse, error)
	mustEmbedUnimplementedScheduleServiceServer()
}

// UnimplementedScheduleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduleServiceServer struct{}

func (UnimplementedScheduleServiceServer) GetFaculties(context.Context, *Empty) (*FacultiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFaculties not implemented")
}
func (UnimplementedScheduleServiceServer) GetGroups(context.Context, *GroupsRequest) (*GroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroups not implemented")
}
func (UnimplementedScheduleServiceServer) GetSchedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) GetLastUpdated(context.Context, *Empty) (*LastUpdatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastUpdated not implemented")
}
func (UnimplementedScheduleServiceServer) GetScheduleByPath(context.Context, *SGUPathRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduleByPath not implemented")
}
func (UnimplementedScheduleServiceServer) RunScrape(context.Context, *Empty) (*ScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScrape not implemented")
}
func (UnimplementedScheduleServiceServer) GetScrapeStatus(context.Context, *Empty) (*ScrapeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScrapeStatus not implemented")
}
func (UnimplementedScheduleServiceServer) mustEmbedUnimplementedScheduleServiceServer() {}
func (UnimplementedScheduleServiceServer) testEmbeddedByValue()                         {}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	// If the following call panics, it indicates UnimplementedScheduleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_GetFaculties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetFaculties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetFaculties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetFaculties(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetGroups(ctx, req.(*GroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetSchedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetLastUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetLastUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetLastUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetLastUpdated(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetScheduleByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGUPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetScheduleByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetScheduleByPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetScheduleByPath(ctx, req.(*SGUPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_RunScrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).RunScrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_RunScrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).RunScrape(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetScrapeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetScrapeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetScrapeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetScrapeStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFaculties",
			Handler:    _ScheduleService_GetFaculties_Handler,
		},
		{
			MethodName: "GetGroups",
			Handler:    _ScheduleService_GetGroups_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _ScheduleService_GetSchedule_Handler,
		},
		{
			MethodName: "GetLastUpdated",
			Handler:    _ScheduleService_GetLastUpdated_Handler,
		},
		{
			MethodName: "GetScheduleByPath",
			Handler:    _ScheduleService_GetScheduleByPath_Handler,
		},
		{
			MethodName: "RunScrape",
			Handler:    _ScheduleService_RunScrape_Handler,
		},
		{
			MethodName: "GetScrapeStatus",
			Handler:    _ScheduleService_GetScrapeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/schedule.proto",
}
